//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ReportedByUserId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> ReportedAt { get; set; }
    
        public virtual JobPost JobPost { get; set; }
        public virtual User User { get; set; }
    }
}
